### ISSUE TITLE
Variable for font(s)

### ISSUE THREAD

**Issue by ShayBox** [redsauce117/SauceysDiscordThemes#2]
Have a variable to allow users to set the font(s)

**Comment by sauceysaucer** [comment]
Not a bad idea. I think I will look into that and include it in a future update. Thanks for the suggestion. A faster way to contact me would be directly through discord though! Saucey#9999

**Comment by ShayBox** [comment]
Oh, you should update the readme with your new discrim

**Comment by sauceysaucer** [comment]
I'm already planing on it after my Nitro subscription ends.
