### ISSUE TITLE
Chat Background Not Changing

### ISSUE THREAD

**Issue by NotTylr** [redsauce117/SauceysDiscordThemes#4]
![9bwrg7d](https://user-images.githubusercontent.com/44178945/46977134-2f22c800-d080-11e8-93cb-9766a0b2e08a.png)

**Comment by ShayBox** [comment]
Theme be dead sad :disappointed:

**Comment by sauceysaucer** [comment]
I stopped working on this theme a while back, I know it was a hit, so i'm sorry to have to let it go ):
